### ISSUE TITLE
include json station files with package

### ISSUE THREAD

**Issue by jlkittle** [neroden/timetable_kit#2]
include json station files with package or be a bit more explicit that they must be downloaded before timetables can be generated.

**Comment by neroden** [comment]
Since Amtrak's station database changes frequently, I encourage people to download them themselves.  Documentation is in a state of flux since none of the interfaces are stabilized, but I agree the download process should be better documented.

**Comment by neroden** [comment]
Download process documented, and instructions that it must be done are now explicit in multiple places.
