### ISSUE TITLE
improve README - describe arguments to main; reference tt-spec-documentation.txt, where to get AMTRAK gtfs

### ISSUE THREAD

**Issue by jlkittle** [neroden/timetable_kit#4]
improve README.rst

1. describe arguments to main - gtfs, spec
2. reference tt-spec-documentation.txt 
3. describe where to get gtfs file (https://www.transit.land/feeds/f-9-amtrak~amtrakcalifornia~amtrakcharteredvehicle - referenced in output)

**Comment by neroden** [comment]
On the to do list.  The interfaces are still in a severe state of flux and I haven't been polishing the documentation since it's changing so fast.

**Comment by neroden** [comment]
Done.
