### ISSUE TITLE
Possible station list edge case

### ISSUE THREAD

**Issue by cpbnj** [neroden/timetable_kit#7]
This may be an Amtrak GTFS issue, but I've noticed that in the Crescent timetables posted on narprail.org, the suburban New Jersey stops (Princeton Jct, New Brunswick, Metropark) for train 20 are not listed. I believe those stops were added in Oct 2021. If not a GTFS issue, this could be an edge case where a train pair makes different stops in each direction.

**Comment by neroden** [comment]
I might have missed them because train 21 doesn't stop there.  But it's probably a GTFS issue.  I'm currently waiting for new GTFS since there are a bunch of known bugs in the current GTFS.  :-(  Will check on this when I get back to working on this.

-- 
  Nathanael C. Nerode
  ***@***.***

**Comment by cpbnj** [comment]
Perhaps Amtrak will someday realize that sunlight is the best disinfectant
and will publish their buggy GTFS data for public consumption and feedback.
Thank you for taking the time to create this open source toolkit and for
the excellent timetables you produced with it.

**Comment by neroden** [comment]
They're in the GTFS, I just missed them because they're only stops in one direction and I looked at the other direction.

Fixed with https://github.com/neroden/timetable_kit/commit/347d7b245ec60c88f90683c60c0c75313f7a16d8
